# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - deployment: DeployWeb
    displayName: deploy Web App
    pool:
      vmImage: 'Ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world
          - task: VSTest@2
            inputs:
              platform: '$(buildPlatform)'
              configuration: '$(buildConfiguration)'

          - task: NuGetToolInstaller@1
          - task: NuGetCommand@2
            inputs:
              restoreSolution: '$(solution)'

          - task: VSBuild@1
            inputs:
              solution: '$(solution)'
              msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
              platform: '$(buildPlatform)'
              configuration: '$(buildConfiguration)'

- stage: SlotA
  displayName: Deploy to slot A
  jobs:
  - deployment: DeployWeb
    environment: Slot A
  - job: Build # Build & Test
    steps:


    - task: AzureRmWebAppDeployment@4
      displayName: Deploy to slot A
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Pay-As-You-Go Dev/Test(1ad2775d-4cce-4170-a27e-814087092b90)'
        appType: 'webApp'
        WebAppName: 'contoso-crafts-sjo'
        deployToSlotOrASE: true
        ResourceGroupName: 'contoso-crafts'
        SlotName: 'SlotA'
        packageForLinux: '$(build.artifactStagingDirectory)\WebApp.zip'

    - task: AzureAppServiceManage@0
      inputs:
        azureSubscription: 'Pay-As-You-Go Dev/Test(1ad2775d-4cce-4170-a27e-814087092b90)'
        Action: 'Swap Slots'
        WebAppName: 'contoso-crafts-sjo'
        ResourceGroupName: 'contoso-crafts'
        SourceSlot: 'SlotA'

- stage: SlotB
  displayName: Deploy to slot B
  jobs:
  - deployment: DeployWeb
    environment: Slot B
  - job: Build # Build & Test
    steps:
    - task: AzureRmWebAppDeployment@4
      displayName: Deploy to slot B
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Pay-As-You-Go Dev/Test(1ad2775d-4cce-4170-a27e-814087092b90)'
        appType: 'webApp'
        WebAppName: 'contoso-crafts-sjo'
        deployToSlotOrASE: true
        ResourceGroupName: 'contoso-crafts'
        SlotName: 'SlotB'
        packageForLinux: '$(build.artifactStagingDirectory)\WebApp.zip'

    - task: AzureAppServiceManage@0
      inputs:
        azureSubscription: 'Pay-As-You-Go Dev/Test(1ad2775d-4cce-4170-a27e-814087092b90)'
        Action: 'Swap Slots'
        WebAppName: 'contoso-crafts-sjo'
        ResourceGroupName: 'contoso-crafts'
        SourceSlot: 'SlotB'